language: ruby
sudo: false
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
  matrix:
    - RAILS_VERSION="~> 4.2.8"
    - RAILS_VERSION="~> 5.0.6"
    - RAILS_VERSION="~> 5.1.4"
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.7.0
matrix:
  exclude:
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.0.6"
    - rvm: jruby-19mode
      env: RAILS_VERSION="~> 5.0.6"
    - rvm: jruby-9.1.7.0
      env: RAILS_VERSION="~> 5.0.6"
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.1.4"
    - rvm: jruby-19mode
      env: RAILS_VERSION="~> 5.1.4"
    - rvm: jruby-9.1.7.0
      env: RAILS_VERSION="~> 5.1.4"
